### ISSUE TITLE
Dependency injection example to add services?

### ISSUE THREAD

**Issue by emcengineer** [gotzmann/comet#11]
Really love the speed and simplicity of the framework as I'm testing it out. Keep it up.

Can you provide an example for dependency injection to add services? I'm referencing the slim framework example, but we cannot create the app with the AppFactory::create() method.

https://www.slimframework.com/docs/v4/concepts/di.html

Thanks.

**Comment by emcengineer** [comment]
Figured it out. Just combined Slim docs with PHP DI docs.

**Comment by devudopw** [comment]
> Figured it out. Just combined Slim docs with PHP DI docs.

Can you share some code snippet for this?
I am trying to inject DI container to Comet.
