### ISSUE TITLE
Simple Hello world app example?

### ISSUE THREAD

**Issue by mprog54** [gotzmann/comet#14]
Здравствуйте! Можете скинуть базовый пример приложения Hello world на вашем фреймворке c подключением к БД MySQL?

**Comment by gotzmann** [comment]
Скоро будет обновление документации с примерами обращения к базе через Eloquent ORM.
Более простой и быстрый способ работы через PDO можно подсмотреть в репозитории Techempower Benchmarrks:
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/PHP/comet

**Comment by hrustbb2** [comment]
О май гад!! Только не Eloquent!!! Не тащите этот кошмар в свои проекты пожалуйста
