### ISSUE TITLE
500 error with controller example

### ISSUE THREAD

**Issue by ITwrx** [gotzmann/comet#15]
First, i tried my own controller test, but i was getting a "1" for html source code, but no errors shown in terminal or log (and log successfully logs startup , so it's working). Now, i'm trying the comet controller example, as it's written, and i'm still getting a "1" with no errors logged. When i use curl, it reports a 500 server error. 

thanks

**Comment by ITwrx** [comment]
PHP 7.4.13

**Comment by gotzmann** [comment]
Do you get 500 error with GET or POST request? Please see comment on the docs:

_**Any call with malformed body will be replied with HTTP 500 code**_
