### ISSUE TITLE
Lite version of comet

### ISSUE THREAD

**Issue by aolko** [gotzmann/comet#18]
А можно как-нибудь порезать comet от всякой говны чтобы оставить только библиотеку роутера + авторизацию? __Очень бы не хотелось__ тащить всякий мусор из зависимостей, плюс есть уже свои.
Тем более хотелось бы разворачивать comet на сервере непосредственно, а не как отдельное приложение.

**Comment by gotzmann** [comment]
Comet задумывался как интегрирующий слой поверх Workerman (скорость из коробки) и SlimPHP (минимальный PSR-7 фреймворк из коробки). Выкинуть их невозможно, но остальные компоненты не являются обязательными.

Но композер вроде итак минимальный

    "require": {
        "workerman/workerman": "^4.0",
        "slim/slim": "^4.6",
        "guzzlehttp/psr7": "^1.7",
        "rakit/validation": "^1.4"
    },

Для рабочего приложения в любом случае обычно еще нужно добавить ORM, шаблонизатор, модуль авторизации.

**Comment by gotzmann** [comment]
Если нужно работать под Nginx/Apache - надо использовать SlimPHP. Роутинг в Comet именно оттуда :) Comet сам выступает в роли веб-сервера, ему не нужен Nginx/Apache (Nginx можно использовать как прокси-сервер для продакшена).

**Comment by aolko** [comment]
> Если нужно работать под Nginx/Apache - надо использовать SlimPHP. Роутинг в Comet именно оттуда :) Comet сам выступает в роли веб-сервера, ему не нужен Nginx/Apache (Nginx можно использовать как прокси-сервер для продакшена).

не прокатит, так как это фреймворк, а не роутер
