### ISSUE TITLE
Comet вместе с Laravel 8 одном проекте

### ISSUE THREAD

**Issue by 4EPHblN** [gotzmann/comet#24]
У Laravel в цепочке зависимостей guzzlehttp/psr7 v2.0, а у Comet — guzzlehttp/psr7 v1.7, что не дает установить Comet без дополнительных манипуляций и понижения версии guzzlehttp/psr7.

**Comment by gotzmann** [comment]
Убрал зависимость от Guzzle в новом Comet v2.2 - если актуально, было бы интересно узнать об опыте работы в связке с Laravel :)

**Comment by 4EPHblN** [comment]
Зависимости обновил, вроде все норм.
Сейчас тот проект заморожен, потому поделиться опытом не могу, но если подвернется возможность, обязательно поработаю с Comet👍
