### ISSUE TITLE
Логирование в Comet

### ISSUE THREAD

**Issue by 4EPHblN** [gotzmann/comet#25]
При создании экземпляра Comet я определяю логгер:
```php 
// ...
$logger = new Logger('comet');
$logger->pushHandler($stream);

$app = new Comet([
    'host' => $_ENV['COMET_HOST'],
    'port' => $_ENV['COMET_PORT'],
    'logger' => $logger,
]);
```
Я могу писать лог вручную, обратившись к логгеру напрямую:
```php
$logger->error(...);
```
Как мне получить доступ к логгеру, скажем, из контроллера или из любого другого контекста??
```php
class EventController {
    /**
     * @param Comet\Request $request
     * @param Comet\Response $response
     * @param array $args
     * @return Comet\Response
     */
    public function create(Request $request, Response $response, array $args): Response {
        // Экземпляр логгера тут??
    }

    // ...
}
```

**Comment by gotzmann** [comment]
Comet поддерживает DI-контейнер для общих ресурсов, если передать его в конфиге во время создания приложения.

Принципы работы с Dependency Injection можно посмотреть здесь:

https://www.slimframework.com/docs/v4/concepts/di.html

Создать контейнер можно следующим образом:

```
$container = new Container();

$app = new Comet([
    'container' => $container
]);
```
