### ISSUE TITLE
Call to undefined function pcntl_signal() MacOS

### ISSUE THREAD

**Issue by methaqualon** [gotzmann/comet#27]
MacOS

```
$ php app.php start
sh: nproc: command not found
Comet v2.2.0 [0 workers] ready on http://127.0.0.1:9876
Workerman[app.php] start in DEBUG mode

Fatal error: Uncaught Error: Call to undefined function pcntl_signal() in /Users/Desktop/backend/vendor/workerman/workerman/Worker.php:1118
Stack trace:
#0 /Users/Desktop/backend/vendor/workerman/workerman/Worker.php(539): Workerman\Worker::installSignal()
#1 /Users/Desktop/backend/vendor/gotzmann/comet/src/Comet.php(358): Workerman\Worker::runAll()
#2 /Users/Desktop/backend/app.php(16): Comet\Comet->run()
#3 {main}
  thrown in /Users/Desktop/backend/vendor/workerman/workerman/Worker.php on line 1118

```

On pure MacOS. php -v:
`PHP 7.3.24-(to be removed in future macOS) (cli) (built: Dec 21 2020 21:33:25) ( NTS )`

i think we shoulda paste guide to install php-pcntl on installing topic

**Comment by methaqualon** [comment]
Разобрался, мелочные проблемы зависящие от конкретной платформы, не достойно обсуждения. На каждого полный гайд не напишешь (:

Можно поспрашивать про использование на проде? Где-то используется? Сколько держит? Как оно вообще? 
не заброшен проект-то?

**Comment by gotzmann** [comment]
Из больших проектов - до сих пор крутится в Сбердиске (хотя я давно ушел) и в приватном сервисе машинного перевода (десятки - сотни тысяч RPS в день). Держать может гигантские нагрузки на самом деле, утечек памяти или деградации сервиса не замечено за пару лет после рождения :)

**Comment by fanfromzp** [comment]
Приветствую) 
Никак не могу заставить работать comet из докера. После установки все запускается без проблем, но входящие запросы не доходят. Error: connect ECONNREFUSED 127.0.0.1:8080
Пробовал из-под докерфайла, который указан в качестве примера.
