### ISSUE TITLE
Fatal error: Type of Comet\Factory\CometPsr17Factory::$responseFactoryClass must be string

### ISSUE THREAD

**Issue by techalexx** [gotzmann/comet#32]
Попытка создать экземпляр
$app = new Comet\Comet();
сразу выдает такую ошибку

Fatal error: Type of Comet\Factory\CometPsr17Factory::$responseFactoryClass must be string (as in class Slim\Factory\Psr17\Psr17Factory) in /www/vendor/gotzmann/comet/src/Factory/CometPsr17Factory.php on line 6

**Comment by Wedrix** [comment]
The [open pull request](https://github.com/gotzmann/comet/pull/29/commits/7bb200f664e59caf2c99eeaa4f5da2c38d212ebf) fixes this. Just add the type declarations to the file. Waiting on @gotzmann to merge.

**Comment by gotzmann** [comment]
Fixed thanks @Wedrix !
