### ISSUE TITLE
Wrong sample: Expecting string in sample code, but int given

### ISSUE THREAD

**Issue by fugikzl** [gotzmann/comet#33]
I have tried to launch controller sample and caught that error:
_\.....\vendor\gotzmann\comet\src\Stream.php:250 >> fwrite(): Argument #2 ($data) must be of type string, int given_

It's very dumb, cause the exception accurs because of that line from sample:
`$response->getBody()->write(self::$counter);`
And can be solved by:
`$response->getBody()->write((string)self::$counter);`

**Comment by fugikzl** [comment]
Не знаю, стоило ли создавать новый issue ради этого...

**Comment by gotzmann** [comment]
Should be fixed now
