### ISSUE TITLE
Can you show a comparison between Comet and Mezzio, like you have for the other popular frameworks?

### ISSUE THREAD

**Issue by thexpand** [gotzmann/comet#7]

**Comment by gotzmann** [comment]
I've done all benchmarks modifying code of Techempower Benchmarks. Unfortunately, there no codes for Mezzio, so it no so easy for me to benchmark this framework, sorry.

According to another popular benchmark, it slow as hell (#174 out of 182):

https://github.com/the-benchmarker/web-frameworks

**Comment by gotzmann** [comment]
There are the first benchmark of Comet against other frameworks inluding Mezzio:

https://github.com/the-benchmarker/web-frameworks

74 | php (7.4) | comet (0.7) | 66 835 | 70 357 | 70 149
174 | php (7.4) | mezzio (3.2) | 2 854 | 2 912 | 2 976

So, you may see, Comet able to handle requests ~30x faster then Mezzio.
